#!/usr/bin/python
# This script controls a LED's color and shows how to use the 
# astral library to control the LED's brightness depending on
# the position of the sun.
# The color is set depending on the outdoor temperature, in 
# this case retrieved with the ancient but still functional 
# wx200 package connected to my WMR 968 weather station.
import subprocess
import astral 
import datetime
import pytz
mytz = pytz.timezone('US/Pacific')
now = datetime.datetime.now()
now = mytz.localize(now)
# print "TZ: ", mytz
# print "NOW: ", now
a = astral.Astral()
a.solar_depression = 'civil'
sun = a['San Francisco'].sun(now,local=True)
bright = '1' 
if now > sun['dusk']:
        # lower bright to 1
        bright = '1'
elif now > sun['sunset']:
        # "It's after sunset: ", now, sun['dawn']
        # lower bright to 5
        bright = '5'
elif now > sun['sunrise']:
        # "It's after dawn: ", now, sun['dawn']
        # raise bright
        bright = '25'
elif now > sun['dawn']:
        # "It's after dawn: ", now, sun['dawn']
        # raise bright
        bright = '5'
tout = float(subprocess.check_output(["/usr/local/bin/wx200","--temp","-u","--F"]))
rain = float(subprocess.check_output(["/usr/local/bin/wx200","--nounits","--in/h","--rate"]))
if tout > 96.0:
    subprocess.check_output(["/usr/local/bin/ledcontrol", "MAG", bright])
    subprocess.check_output(["/usr/local/bin/ledcontrol", "GRN", "0"])
elif tout > 80.0:
    subprocess.check_output(["/usr/local/bin/ledcontrol", "GRN", "0"])
    subprocess.check_output(["/usr/local/bin/ledcontrol", "RED", bright])
    subprocess.check_output(["/usr/local/bin/ledcontrol", "BLU", "0"])
elif tout > 56.0:
    subprocess.check_output(["/usr/local/bin/ledcontrol", "GRN", bright])
    subprocess.check_output(["/usr/local/bin/ledcontrol", "RED", "0"])
    subprocess.check_output(["/usr/local/bin/ledcontrol", "BLU", "0"])
elif tout > 32.0:
    subprocess.check_output(["/usr/local/bin/ledcontrol", "GRN", "0"])
    subprocess.check_output(["/usr/local/bin/ledcontrol", "RED", "0"])
    subprocess.check_output(["/usr/local/bin/ledcontrol", "BLU", bright])
else:
    subprocess.check_output(["/usr/local/bin/ledcontrol", "CYN", bright])
    subprocess.check_output(["/usr/local/bin/ledcontrol", "RED", "0"])

if rain > 0.0:
    subprocess.check_output(["/usr/local/bin/ledcontrol", "WHT", bright])
else:
    subprocess.check_output(["/usr/local/bin/ledcontrol", "WHT", "0"])

